# -*- python -*-
import os, fnmatch

from lsst.sconsUtils import scripts, env

pkg = env["packageName"]
sources = []
for top in ("../src/cluster", "../src/utils", "../src/match"):
    for root, dirs, files in os.walk(top):
        sources += [os.path.join(root, f) for f in fnmatch.filter(files, "*.cc")]
        dirs = [d for d in dirs if not fnmatch.fnmatch(d, ".*")]

sources += [os.path.join("../src", s) for s in ("Point.cc", "SpatialUtil.cc", "Time.cc")]

scripts.BasicSConscript.lib(src=sources)
