# -*- python -*-
import re
Import("env")

pkg = env["eups_product"]
env.CheckSwig("python", ilang="c++", includedProducts="base utils pex_exceptions daf_base pex_logging pex_policy security daf_persistence daf_data ndarray afw ap")
env.LoadableModuleIncomplete("_clusterLib", Split("clusterLib.i"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs(pkg))

